### ISSUE TITLE
How to use next-intl on top of this？

### ISSUE THREAD

**Issue by mingzhu-c** [Kiranism/next-shadcn-dashboard-starter#38]

**Comment by Kiranism** [comment]
It's easy since it's a dashboard application; you can simply use the [App Router setup without i18n routing](https://next-intl-docs.vercel.app/docs/getting-started/app-router/without-i18n-routing) .

Examples : https://next-intl-docs.vercel.app/examples#app-router-without-i18n-routing 
Source : https://github.com/amannn/next-intl/tree/main/examples/example-app-router-without-i18n-routing
Demo :  https://next-intl-example-app-router-without-i18n-routing.vercel.app/login

**Comment by mingzhu-c** [comment]
Thanks for your reply, I will give it a try
